services:

  app:
    build: .
    container_name: item-migration-api

    ports:
      - "8080:8080"

    environment:
      MONGO_URI: mongodb://host.docker.internal:27017
      DB_NAME: Item_Migration

    depends_on:
      - mongodb

    restart: always

  mongodb:
    image: mongo:latest

    container_name: mongodb

    ports:
      - "27017:27017"

    volumes:
      - mongo_data:/data/db

    restart: always

volumes:
  mongo_data: